### ISSUE TITLE
IndexError: arrays used as indices must be of integer (or boolean) type

### ISSUE THREAD

**Issue by jolespin** [pog87/PtitPrince#10]
![image](https://user-images.githubusercontent.com/9061708/76024981-de17ac00-5ee0-11ea-8942-83ab79c47ca9.png)

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-103-140a73f05c1a> in <module>
      4 with plt.style.context("seaborn-white"):
      5     fig, ax = plt.subplots(figsize=(13,3))
----> 6     pt.RainCloud(data=df_melt, x="Class", y="Distance", hue="Diversity", palette="Set2", ax=ax)

~/anaconda3/envs/soothsayer_env/lib/python3.6/site-packages/ptitprince/PtitPrince.py in RainCloud(x, y, hue, data, order, hue_order, orient, width_viol, width_box, palette, bw, linewidth, cut, scale, jitter, move, offset, point_size, ax, pointplot, alpha, dodge, linecolor, **kwargs)
    776                     order = order, hue_order = hue_order, palette = palette, move = move,
    777                     edgecolor = "white", size = point_size, jitter = jitter, zorder = 0, dodge = dodge,
--> 778                     width = width_box, ax =ax, **kwrain)
    779 
    780     # Add pointplot

~/anaconda3/envs/soothsayer_env/lib/python3.6/site-packages/ptitprince/PtitPrince.py in stripplot(x, y, hue, data, order, hue_order, jitter, dodge, orient, color, palette, move, size, edgecolor, linewidth, ax, width, **kwargs)
    667                        linewidth=linewidth))
    668 
--> 669     plotter.plot(ax, kwargs)
    670     return ax
    671 

~/anaconda3/envs/soothsayer_env/lib/python3.6/site-packages/ptitprince/PtitPrince.py in plot(self, ax, kws)
     94     def plot(self, ax, kws):
     95         """Make the plot."""
---> 96         self.draw_stripplot(ax, kws)
     97         self.add_legend_data(ax)
     98         self.annotate_axes(ax)

~/anaconda3/envs/soothsayer_env/lib/python3.6/site-packages/ptitprince/PtitPrince.py in draw_stripplot(self, ax, kws)
     68                 cat_pos = self.move + np.ones(strip_data.size) * i
     69                 cat_pos += self.jitterer(len(strip_data))
---> 70                 kws.update(c=palette[point_colors])
     71 
     72                 if self.orient == "v":

IndexError: arrays used as indices must be of integer (or boolean) type
```

It doesn't work.  I'm using `v0.2.3`.  Also, you don't have a `__version__` method.

**Comment by pog87** [comment]
hi @jolespin, thanks for your report.

could you please provide me the version of python, numpy, scipy and seaborn that you are using?

**Comment by jolespin** [comment]
My bad about the delay!

![image](https://user-images.githubusercontent.com/9061708/76451218-591f0d80-638c-11ea-976f-a7bae067df4e.png)

**Comment by pog87** [comment]
> Also, you don't have a __version__ method
for the moment is `pt.PtitPrince.__version__` will fix that at the next release

More importantly: seems that all your packages are fine...
could you please provide some reproducible code that I can run too see where is the issue? 

You can copypaste the code in this way (instead of screenshots..)
\```
import ptitprince as pt
....
....
pt.RainCloud()
\```

**Comment by adamkimbler** [comment]
@pog87 I think this might be an issue with pandas usage. When I use `pt.RainCloud()` with an older `pandas` version (in my test case `pandas==0.25.1`) it raises the `IndexError`, but when I upgraded to `pandas==1.0.3` the error disappeared. It also appears to only affect the `stripplot` functionality, and when I test in a jupyter notebook with `%matplotlib inline` the `violinplot` and `boxplot` are plotted correctly.

**Comment by pog87** [comment]
@adamkimbler ok, I shall add the requirement of `pandas >= 1.0`.

Thank you!

**Comment by jolespin** [comment]
Can you link me to the code that throws an Index error?  I’ll see if I can make it pandas version agnostic.
