### ISSUE TITLE
Attempting to pass 'edgecolor' or 'linewidth' to 'rain_' results in error.

### ISSUE THREAD

**Issue by akimbler** [pog87/PtitPrince#12]
So when I attempt to pass arguments to `stripplot` the current default values appear to be maintained in the function call, which results in my getting the following error.

![image](https://user-images.githubusercontent.com/21314171/78365801-9fcbe600-758d-11ea-9429-8a3e9e3aa703.png)

**Comment by pog87** [comment]
I know exactly how to fix it, but this might take some time...I have higher priority work for now.

please be patient.

**Comment by pog87** [comment]
(after some months) ok, version 0.2.4 fixes the bug you have reported!

thanks for your patience!
