### ISSUE TITLE
cloud_kwargs are not passed on

### ISSUE THREAD

**Issue by sappelhoff** [pog87/PtitPrince#13]
kwargs specified for the clouds are not passed on to the final plotting calls.

The kwargs are first handled here, within `RainCloud`:

https://github.com/pog87/PtitPrince/blob/07960583ba14052ddf1e9777d1420b2275705e86/ptitprince/PtitPrince.py#L744-L755

A bit further down in the code, the cloud kwargs are passed on here to `half_violinplot`: 

https://github.com/pog87/PtitPrince/blob/07960583ba14052ddf1e9777d1420b2275705e86/ptitprince/PtitPrince.py#L757-L762

However, the `half_violinplot` function ignores the kwargs.

https://github.com/pog87/PtitPrince/blob/07960583ba14052ddf1e9777d1420b2275705e86/ptitprince/PtitPrince.py#L673-L688

**Comment by pog87** [comment]
thank you for the report. Version 0.2.4 now passes the kwargs to `plotter.plot` and subfuncitons.

**Comment by sappelhoff** [comment]
Thanks for working on this @pog87 :-)

**Comment by pog87** [comment]
Thank you @sappelhoff  for the best-written Issue I have ever received!
