### ISSUE TITLE
Seaborn.utils functions deprecated

### ISSUE THREAD

**Issue by kgdunn** [pog87/PtitPrince#14]
Hi, in the newest version of seaborn (0.11.0), in the seaborn.utils module, the function "categorical_order" has been removed. Also, the iqr() function will soon be deprecated, according to their code comments.

Since your code imports, but does not use the "categorical_order" function, this can be easily fixed.
The iqr() function is used, but is also available in scipy.stats which you already import, so perhaps switch to that one?

This will greatly help, because at the moment, these conflicts cause other software which use your library to break :(

Thanks.

**Comment by jolespin** [comment]
I'm also getting this error.

**Comment by jolespin** [comment]
I fixed it in this pull request:
https://github.com/pog87/PtitPrince/pull/15

You can just install mine in the meantime:

`pip install --no-deps git+https://github.com/jolespin/PtitPrince`

**Comment by pog87** [comment]
PR accepted, will update pip ASAP
@kgdunn thank you for raising the issue
@jolespin thanks for helping out on this!

**Comment by Jhsmit** [comment]
@pog87 Would it be possible to update the conda version?
I'm running into this issue now since I got version 0.2.3 from conda

**Comment by YukiSakai1209** [comment]
I'm in the same situation. I would be very happy if you could respond as soon as possible.
> @pog87 Would it be possible to update the conda version?
> I'm running into this issue now since I got version 0.2.3 from conda
