### ISSUE TITLE
scikit_posthocs.sign_plot showing significance text table

### ISSUE THREAD

**Issue by legolego** [pog87/PtitPrince#17]
![image](https://user-images.githubusercontent.com/1666188/98769583-38d99f80-23ae-11eb-9fc0-15a41efc2ad0.png)
Hi,
I just started using this library and like it so far, but I'm getting this text table out after calling scikit_posthocs.sign_plot.  Is there a way to not have it show? Or what am I doing wrong? Thank you very much!

**Comment by pog87** [comment]
I think this should be posted on https://github.com/maximtrp/scikit-posthocs/issues
and not here

**Comment by legolego** [comment]
Yes! You're right, I'm sorry, thanks! :)

**Comment by legolego** [comment]
I'm using the Rainclouds but wanted the significance chart next to it , and thanks for even providing the link :)
