### ISSUE TITLE
Showmean in raincloud

### ISSUE THREAD

**Issue by jediknightnapoleon** [pog87/PtitPrince#19]
Hi,

I recently got introduced to this package and found it really nice. However I wonder if there is a way to display the mean without the pointplot lines in the boxplot part of the Raincloud plot?

Many thanks,

Jerry

**Comment by pog87** [comment]
Hi @jediknightnapoleon! 
I'm not 100% sure of what you mean exactly by "display the mean", but if I guess correctly you just want to remove the line in the pointplot, which can be done by adding `point_join=False` in the function call

```
ax=pt.RainCloud( .........,  point_join=False)
```

**Comment by jediknightnapoleon** [comment]
Thank you very much! This is exactly what I meant:)
