### ISSUE TITLE
can raincloud add boxplot with quantiles that we can customize, what percentage of data?

### ISSUE THREAD

**Issue by imronade** [pog87/PtitPrince#21]
If I have data that varies a lot over a very long time span, a raincloud plot would be great if I could add a boxplot with quantiles/ percentiles settings. So that it can increase understanding of the data. thank you

**Comment by pog87** [comment]
You can play with `box_whis` if you want, but I don't recommend it. Viewers suppose the bars to be standard, other choices should be highlighted to avoid consusion.
