### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'asscalar'

### ISSUE THREAD

**Issue by arnavgarg1** [pog87/PtitPrince#26]
I'm running into the following error when trying both `pt.half_violinplot` and `pt.RainCloud`. It seems to be related to the numpy version. 

I'm currently on Numpy 1.23.1, so not sure if there's an issue here - are you able to take a look?

Thanks in advance!

**Comment by arnavgarg1** [comment]
Seems like it requires a pretty simple change: https://numpy.org/doc/1.21/reference/generated/numpy.asscalar.html to just use `numpy.ndarray.item()` instead of `np.asscalar`

**Comment by arnavgarg1** [comment]
I tried this locally and it seems to work without issues :)

**Comment by BrainHackPD** [comment]
I'd be more than happy to review a pull request. thank you for helping!

**Comment by pog87** [comment]
I'd be more than happy to review a pull request. thank you for helping!

**Comment by arnavgarg1** [comment]
Great, no problem! Here's the PR: https://github.com/pog87/PtitPrince/pull/28

**Comment by arnavgarg1** [comment]
Once this is merged in, is it also possible to release a new version of this package to PyPI so the latest changes can be installed via `pip install ptitprince`?
