### ISSUE TITLE
Issue with numpy

### ISSUE THREAD

**Issue by VascoSch92** [pog87/PtitPrince#35]
Hey guys, 

first of all, thanks for this fantastic package :-)

Today I had the following problem:

<img width="1224" alt="Screenshot 2023-04-08 at 18 01 54" src="https://user-images.githubusercontent.com/115561717/230731157-28c0d7be-951e-4913-af63-e9c836ea121f.png">

Are you aware of it?

I wish you a good day and Easter.
V

**Comment by pog87** [comment]
solved by @hyruuk. Thank you!
