### ISSUE TITLE
boxplot median/mean lines 

### ISSUE THREAD

**Issue by matthewvowels1** [pog87/PtitPrince#37]
In the python tutorial, there is an example where you use the hue argument to create a subgroup comparison.

When this is done, the median lines disappear, and are only vaguely visible when the alpha argument is used.

Is it possible to prevent the use of hue from having such a large impact on the boxplots themselves?

Thanks in advance, and it goes without saying that this is a really great package.

**Comment by matthewvowels1** [comment]
P.S. I would add to this that when i reproduce your code (again, when the hue argument gets used to create subgroup comparisons), the alpha argument only gets applied to the density plots, not the boxplots, although this is a slightly different (if somehow related) issue.

**Comment by matthewvowels1** [comment]
P.P.S. I have been able to get around it by adding   plt.setp(ax.patches, alpha=0.5) - this directly 'targets' the boxplot components

**Comment by JPJSea** [comment]
To make the median line visible you can add this to change the zorder: `box_medianprops={"zorder": 11},`

Here is an example which changes the size of the box, makes the median and the mean line visible.
```
ax=pt.RainCloud(x = dx, y = dy, hue = dhue, data = df_rep, palette = pal, bw = sigma, width_viol = .7,
                ax = ax, orient = ort , alpha = .65, dodge = True, pointplot = False, box_meanprops={"zorder" : 11}, 
                box_meanline=True, box_showmeans=True, box_medianprops={"zorder": 11}, width_box=0.25,  move = .2)
```

See the comment on this issue for more information:
https://github.com/RainCloudPlots/RainCloudPlots/issues/51#issuecomment-1023139396
