### ISSUE TITLE
Half violines facing eachother 

### ISSUE THREAD

**Issue by navotnaor** [pog87/PtitPrince#4]
Hi, 
This is a really wonderful package, i was wondering can i have the half violin facing each other? so instead of both of them being the left half, having the left on as it is right now, and the right one be the right half and positioned on the right of the boxplot?

Thank you

**Comment by pog87** [comment]
Hi @navotnaor, and thanks for the interest. What you are asking is hard to write and would lead to a package tot to be used in a general, wide context. To explain it better...what if the group are three instead of two? Two violins facing each other and the other reversed? isn't it ugly to see?
