### ISSUE TITLE
Fix point height

### ISSUE THREAD

**Issue by PierreGtch** [pog87/PtitPrince#43]
Hey,
The point height was not correct in my plots. 

But it seems to be fixed by updating this line:
https://github.com/pog87/PtitPrince/blob/e293e878017793922fb9a36fc8fc9b9895319aac/ptitprince/PtitPrince.py#L770
to:
```python
n_cat = len(np.unique(data[hue]))
sns.pointplot(..., dodge=width_box * (1 - 1 / n_cat), ...)
```

(I used the comment in this tutorial: https://seaborn.pydata.org/examples/jitter_stripplot.html)

**Comment by pog87** [comment]
that looks better than I was doing! feel free to open a pr, I'll try it out before approval. thank you for pointing this out
