### ISSUE TITLE
Error with data type and points not showing

### ISSUE THREAD

**Issue by scienception** [pog87/PtitPrince#45]
Hi I have this error:
AttributeError: module 'numpy' has no attribute 'bool'

Also, when using the sample set simdat.csv the stripplot doesn't even appear.
It used to work for me last year, not sure what happened :(

BTW thanks a lot for creating this amazing package!

Python 3.11.4 
and current version of PtitPrince.

**Comment by pog87** [comment]
upgrading to last version should fix this.

**Comment by scienception** [comment]
I already have the latest version:
<img width="837" alt="Screenshot 2023-10-26 at 17 29 54" src="https://github.com/pog87/PtitPrince/assets/31531090/8e008c14-0de1-4826-97cb-f3bf3fa4af54">

**Comment by pog87** [comment]
could you provide a minimal (non) working example along with the error thrown and the line of code that causes it?
I cannot reproduce your error.
