### ISSUE TITLE
`ax` and `color` options don't work properly

### ISSUE THREAD

**Issue by jolespin** [pog87/PtitPrince#5]
It should be on the first `ax` in my `axes` list and the color should all be `gray`. 

Also, please add a `__version__` attribute.
```python
with plt.style.context("seaborn-white"):
    fig, axes = plt.subplots(figsize=(13,5), ncols=2)
    pt.RainCloud(data=df_small, x="Isolate", y="GC-Content",  color="gray", linewidth=0.618, ax=axes[0])
```

![image](https://user-images.githubusercontent.com/9061708/61559686-1e442000-aa1f-11e9-8834-3aa94344b19f.png)

**Comment by pog87** [comment]
thank you for your suggestion!
I have just rewrote the code to fulfill your requirements.

**Comment by saurabhr** [comment]
the axes for subplot still seem to not work:
```
f, ax = plt.subplots(1,3,figsize=(12, 5))
for i in range(len(col_names)):
    dfi = df['both']['dj'][df['both']['dj']['delay']==col_names[i]]
    pt.RainCloud(x = 'contingency', y = 'estimate', hue = 'intention', data = dfi, \
                      ax=ax[i], bw = .5, width_viol = .7,\
                alpha = .65, dodge = True)

```
Also how to avoid the cutting  of cloud on the left side of the third subplot?
![raincloudplot](https://user-images.githubusercontent.com/63695271/89675433-8ce46c00-d907-11ea-8292-4b6c3b5d43dc.JPG)

**Comment by pog87** [comment]
I honestly can't understand... why did you comment on a closed issue to raise your problem? I found your comment just by accident.

Anyway your coda may be better written as in
https://github.com/pog87/PtitPrince/blob/master/tutorial_python/raincloud_tutorial_python.ipynb

... something like this might work

```python
f, ax = plt.subplots(1,3,figsize=(12, 5))
for i in range(len(col_names)):
    dfi = df['both']['dj'][df['both']['dj']['delay']==col_names[i]]
    ax[i] = pt.RainCloud(x = 'contingency', y = 'estimate', hue = 'intention', data = dfi, \
                      ax=ax[i], bw = .5, width_viol = .7,\
                alpha = .65, dodge = True)
```
