### ISSUE TITLE
Which arguments can I use with PtitPrince?

### ISSUE THREAD

**Issue by Anthr0po1d** [pog87/PtitPrince#50]
Hey there,

Apologies I am rather new to this but love the plots. In general I wonder if there is an overview with the possible arguments that can be used in the RainCloud function within PtitPrince.

For example, I would like to edit the size and placement of the scatterplot and the appearance of the boxplot (filled, placement etc.) but I am unsure whether that is possible.

If it is not possible within PtitPrince, is it possible to use matplotlib or seaborn to affect these paramters?

**Comment by pog87** [comment]
whatever argument you want to pass to e.g. rain is `rain_argument` in the plot. See the home description
