### ISSUE TITLE
set line color of pointplot in `RainCloud()` when `color` argument is not None

### ISSUE THREAD

**Issue by mtnouchi** [pog87/PtitPrince#7]
Hello,

It seems that `color` argument in `RainCloud()` is not working and line color of pointplot is fixed to 'red' here:
https://github.com/pog87/PtitPrince/blob/a650efab6f591e82d14281a92ba50f98f4cdbf10/ptitprince/PtitPrince.py#L768

Could you change this code so that the line color of pointplot is set to `color` when `color` argument is not None?

Thank you

**Comment by pog87** [comment]
Thanks for reporting, I'll fix it asap

**Comment by pog87** [comment]
fixed! the parameter is now called `linecolor`
